language: python
python:
    - "2.7"
    - "2.6"
install:
    - travis_retry pip install . --use-mirrors
    - travis_retry pip install pylast flask --use-mirrors
    - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2 --use-mirrors; fi"
script: nosetests
branches:
    only:
        - master
