library: ~/.beetsmusic.blb
directory: ~/Music

import:
    write: yes
    copy: yes
    move: no
    delete: no
    resume: ask
    incremental: no
    quiet_fallback: skip
    timid: no
    log:
    autotag: yes
    quiet: no
    singletons: no

ignore: [".*", "*~"]
replace:
    - '[\\/]': _
    - '^\.': _
    - '[\x00-\x1f]': _
    - '[<>:"\?\*\|]': _
    - '\.$': _
    - '\s+$': ''
art_filename: cover

plugins: []
pluginpath: []
threaded: yes
color: yes
timeout: 5.0
per_disc_numbering: no
verbose: no

list_format_item: $artist - $album - $title
list_format_album: $albumartist - $album

paths:
    - default: $albumartist/$album%aunique{}/$track $title
    - singleton: Non-Album/$artist/$title
    - comp: Compilations/$album%aunique{}/$track $title
